apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-2va5
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-vevm-tenant/rhtap-demo-app/hacbs-test-project-2va5@sha256:3bfb2dce45f9f21d8b5bd7e7cf172f84335a3b6fed523d43602948e90902f4b4
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
